### ISSUE TITLE
Utilise for-of instead of map-forEach methods to manage async operations

### ISSUE THREAD

**Issue by ymansfarroll** [vladimir1284/fleet-towit#8]
Array iteration methods don't work properly containing async operations inside them. This pattern causes unpredictable behavior during the iteration.

```ts
  baseTenantUsers.map(async(tenantUser) => {
    const tenantContext = tenantPrisma(tenantUser.tenantId);
    const tenant = await tenantContext.tenant.findUnique({where: {id: tenantUser.tenantId}})

    return {...tenantUser, tenant}
})
```

**Comment by vladimir1284** [comment]
@LuisUlloaC , this code needs to be refactored anyway for obtaining the array of {...tenantUser, tenant} directly form prisma query.
