### ISSUE TITLE
FindMany usage in tenantUser table

### ISSUE THREAD

**Issue by ymansfarroll** [vladimir1284/fleet-towit#9]
These UserId aren't intented to be unique across all application, or it's possible to duplicate them across different tenants?

```ts
    const userContext = userPrisma(userId);
    const baseTenantUsers = await userContext.tenantUser.findMany({where:{userId: userId}})
    const augmentedTenantUsers = await Promise.all(
```

**Comment by vladimir1284** [comment]
userId is in fact unique, however, there can be several TenantUser for a single user. A user is binded to an email and their must be unique in the platform. A single user that can have several tenants (maybe owns or admins many businesses). If it has more than one tenant, the user is redirected to a select view for choosing the active one.
